"""G4 one-shot seal authority: identity + hash-chained authority ledger (PR A/A5)."""

from tree_options.seal.errors import (
    ApprovalInvalidError,
    LedgerCorruptError,
    LedgerRootRefusedError,
    SealError,
    SecondExecutionRefusedError,
)
from tree_options.seal.identity import (
    CALENDAR_PENDING,
    CONTENT_IDENTITY_DOMAIN,
    RUNNER_VERSION,
    SEALED_RUN_DOMAIN,
    SealedIdentity,
    content_identity,
    sealed_run_id,
)
from tree_options.seal.ledger import (
    DEFAULT_G4_LEDGER_ROOT,
    GENESIS_PREV,
    KIND_APPROVAL,
    KIND_CONSUMPTION,
    KIND_RECONCILIATION_NOTE,
    LEDGER_DOMAIN,
    LEDGER_FILENAME,
    LedgerRecord,
    LedgerView,
    RecordKind,
    append_approval,
    append_consumption,
    append_reconciliation_note,
    append_record,
    read_ledger,
    validate_ledger_root,
)

__all__ = [
    "CALENDAR_PENDING",
    "CONTENT_IDENTITY_DOMAIN",
    "DEFAULT_G4_LEDGER_ROOT",
    "GENESIS_PREV",
    "KIND_APPROVAL",
    "KIND_CONSUMPTION",
    "KIND_RECONCILIATION_NOTE",
    "LEDGER_DOMAIN",
    "LEDGER_FILENAME",
    "RUNNER_VERSION",
    "SEALED_RUN_DOMAIN",
    "ApprovalInvalidError",
    "LedgerCorruptError",
    "LedgerRecord",
    "LedgerRootRefusedError",
    "LedgerView",
    "RecordKind",
    "SealError",
    "SealedIdentity",
    "SecondExecutionRefusedError",
    "append_approval",
    "append_consumption",
    "append_reconciliation_note",
    "append_record",
    "content_identity",
    "read_ledger",
    "sealed_run_id",
    "validate_ledger_root",
]
