"""OptionsOverlaySpec: the frozen recipe for a synthetic option-chain
overlay (M3 plan §3.A).

An overlay is a pure function of (OptionsOverlaySpec, the parent equity
world's bars/master/actions, calendar). The parent world is generated by
the byte-frozen `synth/` v1 generator and is NEVER touched: the overlay
chains on top of its records. All parameters live HERE — never in the
frozen research protocol, never in `synth/`.

Timing conventions carried by every overlay (mirroring the M3 spike §3):
- session t's option file carries two quote snapshots per contract-day
  (15:45 ET and the close) stamped `exchange_timestamp` intraday on t;
- the file's `received_timestamp` is 09:00 America/New_York on the NEXT
  session (T+1 publication, before a 10:00 ET entry window);
- the last session of the world has no file (its publication instant
  would fall outside the world) — a declared boundary, not a gap.
"""

from __future__ import annotations

from typing import Literal

from pydantic import Field, model_validator

from tree_options.schemas.common import IdStr, StrictModel

PUBLICATION_WALL_TIME_MINUTES = 9 * 60  # 09:00 America/New_York, T+1


class OptionsOverlaySpec(StrictModel):
    overlay_version: Literal["v2"] = "v2"
    world_id: IdStr
    seed: int
    # option-eligible universe: top-N by trailing median dollar volume
    eligible_top_n: int = Field(default=100, ge=10, le=5000)
    eligibility_window_bars: int = Field(default=20, ge=5, le=252)
    min_eligible_bars: int = Field(default=5, ge=1, le=252)
    # strike ladder: log-spaced moneyness nodes snapped to the exchange grid
    n_moneyness_nodes: int = Field(default=21, ge=5, le=101)
    moneyness_span: float = Field(default=0.30, gt=0.05, lt=0.9)
    # chain composition: nearest `max_live_expiries` by DTE
    max_live_expiries: int = Field(default=10, ge=2, le=40)
    weekly_listing_dte: int = Field(default=70, ge=5, le=400)
    quarterly_listing_dte: int = Field(default=397, ge=60, le=1200)
    # pricing (Black-Scholes with the planted IV; analytic delta)
    risk_free: float = Field(default=0.03, ge=0.0, lt=0.20)
    dividend_yield: float = Field(default=0.0, ge=0.0, lt=0.20)
    iv_base_min: float = Field(default=0.16, gt=0.01, lt=3.0)
    iv_base_max: float = Field(default=0.42, gt=0.01, lt=3.0)
    iv_expiry_mult_min: float = Field(default=0.85, gt=0.1, lt=10.0)
    iv_expiry_mult_max: float = Field(default=1.25, gt=0.1, lt=10.0)
    # spread model: half-spread fraction of mid = atm * (1 + wing * |ln(S/K)|)
    atm_half_spread_fraction: float = Field(default=0.015, gt=0.0, lt=0.5)
    wing_spread_scale: float = Field(default=4.0, ge=0.0, le=50.0)
    # liquidity shape (OI/volume concentrated ATM / short tenor)
    oi_base_atm: float = Field(default=2500.0, gt=0.0)
    oi_moneyness_width: float = Field(default=0.03, gt=0.0)
    oi_tenor_days: float = Field(default=180.0, gt=0.0)
    untraded_fraction: float = Field(default=0.5, ge=0.0, le=1.0)
    non_tradable_fraction: float = Field(default=0.01, ge=0.0, lt=0.5)
    underlying_half_spread_bps: int = Field(default=5, ge=0, le=500)
    quote_source: IdStr = "synthetic-options-v2"

    @model_validator(mode="after")
    def _ordered_ranges(self) -> OptionsOverlaySpec:
        if self.iv_base_min >= self.iv_base_max:
            raise ValueError("iv_base_min must be < iv_base_max")
        if self.iv_expiry_mult_min >= self.iv_expiry_mult_max:
            raise ValueError("iv_expiry_mult_min must be < iv_expiry_mult_max")
        if self.min_eligible_bars > self.eligibility_window_bars:
            raise ValueError("min_eligible_bars must be <= eligibility_window_bars")
        if self.quarterly_listing_dte < self.weekly_listing_dte:
            raise ValueError("quarterly_listing_dte must be >= weekly_listing_dte")
        return self
