#!/usr/bin/env python3
"""Generate (once) the frozen synthetic forecast fixture for RL-3.

The fixture IS truth: a committed immutable artifact with a .sha256
sidecar. This script is PROVENANCE — it documents exactly how the bytes
were produced and can re-derive them for audit (``--check`` reports
drift WITHOUT failing, because numpy Generator streams may change
between versions; the committed bytes and sidecar stand).

Determinism: seed derived from sha256(b"rl3-synthetic-forecast-v1")
(fixed material, not a clock), numpy default_rng, lognormal random walk
from 100.0, levels rounded to 4 decimal places, sessions = the FIRST
750 sessions of the pinned research calendar (well before the 2025
closure quirks — the synthetic lane does not intersect a session
authority).

Usage:
    PYTHONPATH=src python scripts/research/make_synthetic_forecast_fixture.py
    PYTHONPATH=src python scripts/research/make_synthetic_forecast_fixture.py --check
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "src"))

import numpy as np  # noqa: E402

from tree_options.research.comparison.calendar import load_sessions  # noqa: E402

SEED_MATERIAL = b"rl3-synthetic-forecast-v1"
N_SESSIONS = 750
START_LEVEL = 100.0
DRIFT = 0.0002
SIGMA = 0.01
SCHEMA = "research-forecast-fixture/1"
FIXTURE = REPO / "data" / "research" / "fixtures" / \
    "synthetic-forecast-v1.json"


def seed_int() -> int:
    return int.from_bytes(hashlib.sha256(SEED_MATERIAL).digest()[:4], "big")


def build_document() -> dict[str, object]:
    sessions = load_sessions()[:N_SESSIONS]
    rng = np.random.default_rng(seed_int())
    log_levels = np.empty(N_SESSIONS)
    log_levels[0] = np.log(START_LEVEL)
    steps = rng.normal(DRIFT, SIGMA, size=N_SESSIONS - 1)
    log_levels[1:] = log_levels[0] + np.cumsum(steps)
    levels = [round(float(np.exp(v)), 4) for v in log_levels]
    return {
        "schema": SCHEMA,
        "source_id": "synthetic-forecast-v1",
        "sessions": [s.isoformat() for s in sessions],
        "levels": levels,
        "generator": {
            "kind": "lognormal-random-walk",
            "seed_material": SEED_MATERIAL.decode(),
            "seed": seed_int(),
            "start_level": START_LEVEL,
            "drift": DRIFT,
            "sigma": SIGMA,
            "numpy": np.__version__,
            "round_dp": 4,
        },
    }


def render(doc: dict[str, object]) -> bytes:
    return (json.dumps(doc, indent=2, sort_keys=True) + "\n").encode()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="report drift against the committed fixture "
                             "without failing (fixture is truth)")
    args = parser.parse_args()

    doc = build_document()
    body = render(doc)
    sha = hashlib.sha256(body).hexdigest()

    if args.check:
        if not FIXTURE.is_file():
            print(f"ABSENT: {FIXTURE}")
            return 0
        committed = FIXTURE.read_bytes()
        committed_sha = hashlib.sha256(committed).hexdigest()
        if committed_sha == sha:
            print(f"OK: regenerated bytes match the committed fixture "
                  f"({sha[:16]}...)")
        else:
            sidecar = FIXTURE.with_name(FIXTURE.name + ".sha256")
            print(f"DRIFT: regenerated {sha[:16]}... vs committed "
                  f"{committed_sha[:16]}... (sidecar "
                  f"{sidecar.read_text().strip()[:16]}...). The committed "
                  f"bytes stand; regenerate only deliberately, then update "
                  f"the sidecar and every dependent receipt.")
        return 0

    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_bytes(body)
    sidecar = FIXTURE.with_name(FIXTURE.name + ".sha256")
    sidecar.write_text(sha + "\n")
    print(f"wrote {FIXTURE} ({len(body)} bytes) + sidecar {sha}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
